### PR TITLE
1021/http api root

### PR DESCRIPTION
**Pull request by libscott**
`/` and `/api/v1` endpoints for #1021

### CODE REVIEW

**Comment by diminator** [comment]
perfect

trailing slashes or not?

**Comment by sohkai** [comment]
> trailing slashes or not?

I think we previously set it up to be usable on both (so it should still work with both)?

**Comment by diminator** [comment]
it works with both `strict_slashes=False`

**Comment by libscott** [comment]
I'm kind of in favor of redirecting to include the slash, being finicky about not having duplicate URLs these days, any opinions?

**Pull request merged**
