### PR TITLE
Rename validity to blocks_validity_status

### LINKED ISSUE #679: Rename variable "validity" to more descriptive name, such as "block_statuses"
Some parts of the code have this variable `validity` which stores a dictionary of block ids, and their statuses. The word `validity` is somewhat nebulous once one knows what it actually holds.

See https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/core.py#L215 for instance.

### PR DESCRIPTION
**Pull request by ketanbhatt**
Fixes #679

### CODE REVIEW

**Comment by ttmc** [comment]
Hi @ketanbhatt 

Before we can merge this pull request, we need you or your organization to agree to one of our contributor agreements. One of the big concerns for people using and developing open source software is that someone who contributed to the code might claim the code infringes on their copyright or patent. To guard against this, we ask all our contributors to sign a Contributor License Agreement. This gives us the right to use the code contributed and any patents the contribution relies on. It also gives us and our users comfort that they won't be sued for using open source software. We know it's a hassle, but it makes the project more reliable in the long run. Thank you for your understanding and your contribution!

If you are contributing on behalf of yourself (and not on behalf of your employer or another organization you are part of) then you should:

1. Go to: https://www.bigchaindb.com/cla/
2. Read the Individual Contributor Agreement
3. Fill in the form "For Individuals"
4. Check the box to agree
5. Click the SEND button

If you're contributing as an employee, and/or you want all employees of your employing organization to be covered by our contributor agreement, then someone in your organization with the authority to enter agreements on behalf of all employees must do the following:

1. Go to: https://www.bigchaindb.com/cla/
2. Read the Entity Contributor Agreement
3. Fill in the form "For Organizations”
4. Check the box to agree
5. Click the SEND button

We will email you (or your employer) with further instructions.

**Comment by ketanbhatt** [comment]
@ttmc I have submitted the form

**Comment by ketanbhatt** [comment]
This is to confirm that I agreed to and accepted the BigchainDB Individual Contributor Agreement at https://www.bigchaindb.com/cla/ and to represent and warrant that I have authority to do so.

pzd3CfnK62fosVwNj4Wkxbd57yPdAPvCrP1aY6fFI30pcpztB5Fcfvs8kySfKTw

**Comment by ttmc** [comment]
Thanks @ketanbhatt ! That completes the CLA process.

I assigned @sbellem to review this PR because he created the original issue. He's at EuroPython this week, so he might not get around to reviewing it right away.

**Comment by ketanbhatt** [comment]
@sbellem anything pending on my side?

**Comment by r-marques** [comment]
Hi @ketanbhatt,

Sorry for the delay. @sbellem is on vacation.
The pr looks good to me. We should merge this soon.

**Pull request merged**
