### PR TITLE
improve documentation

### PR DESCRIPTION
**Pull request by r-marques**
@ttmc small modification to the documentation

### CODE REVIEW

**Comment by ttmc** [comment]
That section of the documentation (**Installing BigchainDB Server**) is about installing BigchainDB, although it does also get them to run it, just to make sure it's properly installed.

I'm not sure we want to tell them to do a load test at this point. They might not want to dump a bunch of dummy transactions into their BigchainDB instance. The `bigchaindb-benchmark` command is mentioned in the section **The BigchainDB Command Line Interfaces (CLIs)**.

In any case, I gather that Ryan's new PR adds new benchmarking capabilities.

**Comment by r-marques** [comment]
In @rhsimplex  monitoring documentation it points to how to start bigchaindb so that we can have something appear on the dashboard. That's why I decided to add that line there.

So maybe @rhsimplex  should point to `bigchaindb-cli.html#the-bigchaindb-command-line-interfaces-clis` from his documentation?

**Comment by ttmc** [comment]
I discussed this with @rhsimplex and we decided that he'll add a line or two about calling `bigchaindb-benchmark load` right in his new chunk of documentation (i.e. in context).

**Comment by r-marques** [comment]
ok, so I can disregard this changes and close this pull request?

**Comment by ttmc** [comment]
Yes.

**Pull request closed without merging**
