### PR TITLE
Docs: changed instructions for running unit tests

### PR DESCRIPTION
**Pull request by ttmc**
I simplified the instructions for running all the unit tests, and added some links in an "Aside", so that curious people can easily find out more about pytest and pytest-runner.

### CODE REVIEW

**Comment by r-marques** [comment]
I guess this is the simplest way of running the tests.

:+1:

**Comment by vrde** [comment]
++

merging now

**Comment by sbellem** [comment]
As a note: using `setup.py` to run the tests is somewhat impractical when one needs to pass parameters to `pytest`, as it needs to be done via `--addopts` and is not as straightforward as simply using `py.test`.

**Comment by ttmc** [comment]
@sbellem That section of the documentation is aimed at people who just want some way to make sure that BigchainDB is working properly (by running all unit tests), but they don't intend to do any developing.

@vrde You were going to add some notes to `CONTRIBUTING.md` to help developers get set up for developing / contributing to BigchainDB. Maybe add a note about there about using `py.test -v` or `python -m pytest -v` if they want to do more sophisticated things with pytest?

**Comment by ttmc** [comment]
@vrde Never mind - I see you already submitted PR #180. I'll make some minor edits to that branch and add the suggested comments on pytest at the same time.

**Comment by sbellem** [comment]
@ttmc ok! :+1: Just wanted to share the information, as I had tried both.

**Pull request merged**
