### PR TITLE
Rename "output" to "output_index" in /api/v1/outputs

### PR DESCRIPTION
**Pull request by libscott**
Addresses #1559

### CODE REVIEW

**Comment by r-marques** [comment]
Lets rename it to be consistent with the work we did in the api breaking changes

**Comment by libscott** [comment]
@travis where have you gone

**Comment by TimDaub** [comment]
> @travis where have you gone

Fun fact: @travis is a software dev working for @circleci lol

**Comment by libscott** [comment]
> Fun fact: @travis is someone working for @circleci lol

That is fun. Maybe they should help us out!

**Comment by libscott** [comment]
Ready to go?

Travis says failing above, but when you click Details it is passing.

screenshot from 2017-06-29 15-36-06

**Comment by travis** [comment]
🙌

But unfortunately I'm no longer at CircleCI! They are great tho, that new
workflow stuff is fire.

**Comment by TimDaub** [comment]
> But unfortunately I'm no longer at CircleCI! They are great tho, that new
> workflow stuff is fire.

[We're hiring](https://github.com/bigchaindb/org/blob/master/engjob.md) ;)

**Comment by travis** [comment]
hahaha, that's one of the better recruiter pitches I've seen in a long
time, bravo ;-p not looking for something new right now. I will definitely
look at bigchaindb for a project I'm working on though...

**Pull request merged**
