### PR TITLE
Remove duplicated documentation test code that's been moved to the driver

### LINKED ISSUE #637: Remove duplicate code from python server docs
Related to #607 

For this page: https://bigchaindb.readthedocs.io/en/latest/drivers-clients/python-server-api-examples.html
We have the markdown file itself:
- https://github.com/bigchaindb/bigchaindb/blob/master/docs/source/drivers-clients/python-server-api-examples.md

but additionally, we also have a Python file that can be run to _test_ the code examples in the markdown file:
- https://github.com/bigchaindb/bigchaindb/blob/master/tests/doc/run_doc_python_server_api_examples.py

As updating both files when making changes to the BigchainDB API is quite elaborate, it would be nice if we could:
- run the tests somehow against the .md file
- extract the python code snippets automatically from the file and test directly against them

/cc @ttmc: Maybe you explored this already?

### PR DESCRIPTION
**Pull request by sohkai**
Fixes #637 

We've already removed the actual documentation, and other tests should already be covering the use cases in this test.

@sbellem I'm not sure if you're still using this file for the driver, if you are then we can wait (or you can refer to a previous commit when adding more usage cases for the driver).

### CODE REVIEW

**Comment by sbellem** [comment]
:+1:

**Comment by sbellem** [comment]
> @sbellem I'm not sure if you're still using this file for the driver, if you are then we can wait (or you can refer to a previous commit when adding more usage cases for the driver).

We can remove it.

**Comment by ttmc** [comment]
AFAIK @diminator wrote that file of tests to test the BigchainDB Python API by Example page --- a page that is now gone from the docs.

**Comment by diminator** [comment]
@ttmc we'll have to revise that entire test file using the new driver ofc

**Comment by ttmc** [comment]
@diminator :

@sbellem copied all those examples over to the Python driver docs page about "Advanced Usage" with notes about what's not supported yet: see https://docs.bigchaindb.com/projects/py-driver/en/latest/advanced-usage.html 

Maybe you can share some ideas with him about how to test those.

**Pull request merged**
