### PR TITLE
Added v0.1.5 and more to CHANGELOG.md

### PR DESCRIPTION
**Pull request by ttmc**
Added the v0.1.5 release information.

Added a bunch of stuff to the "Unreleased version" (to be v0.2.0).

Still to do (at the time this PR was created):  

- [x] List external contributors

### CODE REVIEW

**Comment by r-marques** [comment]
great :+1: 

I guess that we could wait and change the `unreleased` to `0.2.0` and merge this before releasing the new version

**Comment by ttmc** [comment]
I added mention of all external contributors (and their pull requests) in `CHANGELOG.md`. They go under the sub-heading **External Contributors**.

**Comment by r-marques** [comment]
@ttmc maybe we merge this now and then change the release title in the release branch

**Comment by ttmc** [comment]
@r-marques I can change "Unreleased" to "v0.2.0" in `CHANGELOG.md` (and put the date as 2016-04-25) but I won't know the commit hash or exact commit time until after the commit. Also, I don't know what you mean by "change the release title in the release branch".

**Comment by r-marques** [comment]
@ttmc when creating a new release we usually create a new branch and do some things like bumping the release version.

We can merge this now as is and before releasing we change the changelog together with the new version number

**Comment by ttmc** [comment]
Okay got it, merging now...

**Pull request merged**
