### PR TITLE
[WIP Do Not Merge] Api/601/expose bigchaindb functionality

### PR DESCRIPTION
**Pull request by diminator**
**UPDATE SEE: https://github.com/bigchaindb/bigchaindb/pull/624#issuecomment-259408517**

- [x] `get_owned_ids` -> `GET /transactions/unspents/{owner_id}`
- [ ] `get_block`
- [ ] `get_votes`

### CODE REVIEW

**Comment by ttmc** [comment]
Using words like "owner" and `owner_id` is misleading. The list you'll get back is a list of all unspent assets where the holder of the passed public key has some capability to cause a valid transfer (but the key holder might not actually own any of those assets). This is already discussed elsewhere, e.g. in issue #626

**Comment by TimDaub** [comment]
I'm gonna take this PR over and implement according to [this proposal](https://github.com/bigchaindb/bigchaindb/issues/601#issuecomment-259161817).

Specifically:

`get_owned_ids`: `HTTP GET /transactions?owner_after=1AAAbbb...ccc`

Returns a list of transaction (full body).

```
 get_block
 get_votes
```

Will be implemented in other PRs.

Any objections? @sbellem @sohkai?

**Comment by TimDaub** [comment]
Closing this in favor of #818

**Comment by diminator** [comment]
@TimDaub can you also check to move the changes to the documentation?

**Comment by TimDaub** [comment]
> @TimDaub can you also check to move the changes to the documentation?

Docs were handled here: #803

**Pull request closed without merging**
