### PR TITLE
Update the Quickstart page

### PR DESCRIPTION
**Pull request by ttmc**
- The URL of the "Get Started" page changed so I updated that.
- The testnet.bigchaindb.com site is going away (because it's hosted by 3scale) and the BigchainDB "Get Started" page will have all the information they'll need to connect to the BigchainDB Testnet, so just link there.
- The "Old Quickstart" subsection isn't really needed any more because:
  - The BigchainDB "Get Started" page will have a prominent link to "Install BigchainDB Server" and it will link to the [Simple Deployment Template](http://docs.bigchaindb.com/projects/server/en/master/simple-deployment-template/index.html).
  - The [Simple Deployment Template](http://docs.bigchaindb.com/projects/server/en/master/simple-deployment-template/index.html) follows soon after the Quickstart page in the table of contents.

### CODE REVIEW

**Comment by ttmc** [comment]
On second thought, this PR could be merged now, since it's consistent with how things work now, and how things _will_ work in the future.

**Comment by vrde** [comment]
Looks good to me. I think we should keep a link on how to run a local node as a secondary option.

**Comment by ttmc** [comment]
Okay I added links to docs about how to deploy a local node.

**Comment by ttmc** [comment]
Codecov#$!$%&###!!

**Pull request merged**
