### PR TITLE
Tests for issue 27

### PR DESCRIPTION
**Pull request by sbellem**
Main goal of this PR is to solve issue #27.

### CODE REVIEW

**Comment by vrde** [comment]
Apparently, if I **reinsert** the bug, the test suite passes. Check out my example here.

## Reinsert the bug
```
vrde@pulp ~/ascribe/repos/bigchaindb (b'tests-for-issue-27'|✚1)
 bigchain % git diff
diff --git a/bigchaindb/core.py b/bigchaindb/core.py
index d6669f7..823d484 100644
--- a/bigchaindb/core.py
+++ b/bigchaindb/core.py
@@ -7,7 +7,7 @@ import rapidjson
 from datetime import datetime
 
 import bigchaindb
-import bigchaindb.config_utils
+# import bigchaindb.config_utils
 from bigchaindb import exceptions
 from bigchaindb.crypto import hash_data, PublicKey, PrivateKey, generate_key_pair
 ```

## Run the tests (all green!)
```
vrde@pulp ~/ascribe/repos/bigchaindb (b'tests-for-issue-27'|✚1)
 bigchain % py.test 
============================= test session starts ==============================
platform linux -- Python 3.4.3+, pytest-2.8.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/vrde/ascribe/repos/bigchaindb, inifile: pytest.ini
plugins: cov-2.2.0, xdist-1.14
collected 73 items 

tests/test_core.py ..
tests/db/test_bigchain_api.py s...........ssss..............s....................s
tests/db/test_utils.py ......
tests/db/test_voter.py ......s...s
tests/utils/test_config_utils.py ..

==================== 64 passed, 9 skipped in 74.34 seconds =====================
```

## Try to create a Bigchain instance
```
vrde@pulp ~/ascribe/repos/bigchaindb (b'tests-for-issue-27'|✚1)
 bigchain % python
Python 3.4.3+ (default, Oct 14 2015, 16:03:50) 
[GCC 5.2.1 20151010] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import bigchaindb
>>> bigchaindb.Bigchain()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vrde/ascribe/repos/bigchaindb/bigchaindb/core.py", line 49, in __init__
    bigchaindb.config_utils.autoconfigure()
AttributeError: 'module' object has no attribute 'config_utils'
>>> 
```

# Why this happens
I suppose this happens because of the **autodiscover** feature of `py.test`. If I add a print in `test_bigchain_api.py`:
```
vrde@pulp ~/ascribe/repos/bigchaindb (b'tests-for-issue-27'|✚2)
 bigchain % git diff tests/db/test_bigchain_api.py 
diff --git a/tests/db/test_bigchain_api.py b/tests/db/test_bigchain_api.py
index f4ba8ce..e8491c8 100644
--- a/tests/db/test_bigchain_api.py
+++ b/tests/db/test_bigchain_api.py
@@ -13,6 +13,7 @@ from bigchaindb.voter import Voter
 from bigchaindb.block import Block
 
 import bigchaindb.config_utils
+print('*** import test_bigchain_api.py ***')
```

and if I run the test suite again:
```
vrde@pulp ~/ascribe/repos/bigchaindb (b'tests-for-issue-27'|✚2)
 bigchain % py.test -s                            
================================ test session starts ================================
platform linux -- Python 3.4.3+, pytest-2.8.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/vrde/ascribe/repos/bigchaindb, inifile: pytest.ini
plugins: cov-2.2.0, xdist-1.14
collecting 2 items*** import test_bigchain_api.py ***
collected 73 items 

tests/test_core.py ..
```

you can see how `py.test`, in order to collect the tests to run, loads the `test_bigchain_api` module. The `test_bigchain_api` module imports `bigchaindb.config_utils`, changing the attributes of the `bigchaindb` module (i.e. adding the attribute `config_utils` to `bigchaindb`). From now on, `bigchaindb.config_utils` is defined.

## Ideas on how to actually write a test for this bug
Might be ugly, but we can spawn a process that is just `python -c 'import bigchaindb; bigchaindb.Bigchain()'` and see if it fails or not. I truly believe that spawning a fresh python interpreter is the only way to avoid this.

**Comment by sbellem** [comment]
oh sorry, must have missed something, 

if you import `config_utils` locally, it works

**Comment by sbellem** [comment]
@vrde please try the proposed changes

**Comment by sbellem** [comment]
Related reading:

* https://palladion.com//home/tseaver/obzervationz/2008/unit_testing_notes-20080724
* http://docs.pylonsproject.org/en/latest/community/testing.html

**Comment by sbellem** [comment]
the following resource may be of some help: http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html

**Comment by vrde** [comment]
> the following resource may be of some help: http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html#the-submodules-are-added-to-the-package-namespace-trap

Great! Thanks for the link! The tests look better now and we can merge.

A couple of ideas on how to improve the tests:
1. before all the tests in `test_commands.py` we can check **as a precondition** that `bigchain.config_utils` is defined (and fail the test otherwise);
2. try to run `python -c 'import bigchaindb; bigchaindb.Bigchain()'` in a new process and check the result.

image

**Pull request merged**
