### PR TITLE
Fix broken travis build

### LINKED ISSUE #1683: RethinkDB install fails on Travis
Tests from my (non-related) PRs are failing and I have narrowed it down to a RethinkDB install issue.
Logs from Travis:

```
Installing RethinkDB version 2.3.5
rethinkdb: unrecognized service
Executing: /tmp/tmp.k0lS9Gd8H3/gpg.1.sh --recv-keys
--keyserver
hkp://keyserver.ubuntu.com:80
0x3A8F2399
gpg: requesting key 3A8F2399 from hkp server keyserver.ubuntu.com
gpg: key 3A8F2399: public key "RethinkDB Packaging <packaging@rethinkdb.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
W: http://us-central1.gce.archive.ubuntu.com/ubuntu/dists/precise-updates/InRelease: Signature by key 630239CC130E1A7FD81A27B140976EAF437D05B5 uses weak digest algorithm (SHA1)
W: http://us-central1.gce.archive.ubuntu.com/ubuntu/dists/precise-backports/InRelease: Signature by key 630239CC130E1A7FD81A27B140976EAF437D05B5 uses weak digest algorithm (SHA1)
W: http://us-central1.gce.archive.ubuntu.com/ubuntu/dists/precise/Release.gpg: Signature by key 630239CC130E1A7FD81A27B140976EAF437D05B5 uses weak digest algorithm (SHA1)
W: GPG error: http://download.rethinkdb.com/apt precise Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY CF9BDC6F03D1F02B
W: The repository 'http://download.rethinkdb.com/apt precise Release' is not signed.
W: There is no public key available for the following key IDs:
CF9BDC6F03D1F02B  
W: http://downloads-distro.mongodb.org/repo/debian-sysvinit/dists/dist/Release.gpg: Signature by key 492EAFE8CD016A07919F1D2B9ECBEC467F0CEB10 uses weak digest algorithm (SHA1)
W: http://security.ubuntu.com/ubuntu/dists/precise-security/InRelease: Signature by key 630239CC130E1A7FD81A27B140976EAF437D05B5 uses weak digest algorithm (SHA1)
W: http://ppa.launchpad.net/couchdb/stable/ubuntu/dists/precise/Release.gpg: Signature by key 15866BAFD9BCC4F3C1E0DFC7D69548E1C17EAB57 uses weak digest algorithm (SHA1)
W: http://ppa.launchpad.net/git-core/v1.8/ubuntu/dists/precise/Release.gpg: Signature by key E1DD270288B4E6030699E45FA1715D88E1DF1F24 uses weak digest algorithm (SHA1)
0.41s$ sudo apt-get install -y -o Dpkg::Options::='--force-confnew' rethinkdb=$package_version
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  rethinkdb
0 upgraded, 1 newly installed, 0 to remove and 41 not upgraded.
Need to get 14.7 MB of archives.
After this operation, 39.1 MB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  rethinkdb
E: There were unauthenticated packages and -y was used without --allow-unauthenticated
Installing RethinkDB default instance configuration
cp: cannot stat `/etc/rethinkdb/default.conf.sample': No such file or directory
Starting RethinkDB v2.3.5
0.01s$ sudo service rethinkdb start
rethinkdb: unrecognized service
$ rethinkdb --version
/home/travis/.travis/job_stages: line 54: rethinkdb: command not found
```

One of the lines above states that:
`There were unauthenticated packages and -y was used without --allow-unauthenticated`.

So one option might be to add an `--allow-unauthenticated` flag.
Other options are to see the new RethinkDB install steps.

### PR DESCRIPTION
**Pull request by krish7919**
- Use RethinkDB and MongoDB docker containers rather than manually
install packages.

- Fixes #1683

### CODE REVIEW

**Comment by r-marques** [comment]
Looks good to me but I will leave it for @sbellem to approve this pr.

**Comment by krish7919** [comment]
Some references to why we observe better build times using `docker` may be because it runs on GCE where the queue might be smaller. Ref: [here](https://blog.travis-ci.com/2016-09-30-the-day-we-deleted-our-vm-images/).

**Comment by ttmc** [comment]
I'm really not the right person to be reviewing Travis stuff so I removed my named from the list.

**Comment by krish7919** [comment]
I wanted to collect some data points on how the build times were affected (based on your doubts). I looked at all the PRs with completed/successful tests. Here are the results:


| PR Name | PR time | Push Time|
|-------------|------------|------------|
|Fix broken travis build #1684| Ran for 3 min 36 sec Total time 22 min 50 sec | Ran for 2 min 43 sec Total time 23 min 3 sec| 
|Added docs about OMS logging setup via web browser #1671|Ran for 6 min 52 sec  Total time 18 min 46 sec | Ran for 8 min 45 sec Total time 22 min 52 sec|
|Wrote more about how to calculate a fulfillment string #1654|Ran for 12 min  Total time 32 min | Ran for 9 min 19 sec  Total time 33 min 1 sec|
|HTTP API Logger logs request path and method too #1644|Ran for 9 min 3 sec  Total time 32 min 14 sec||
|Rename validity to blocks_validity_status #1643|Ran for 8 min 27 sec Total time 31 min 19 sec||
|More refinements to the release process #1640|Ran for 8 min 47 sec Total time 31 min 49 sec|Ran for 10 min 54 sec  Total time 31 min 49 sec|
|Use more explicit names for docker-compose files #1563|Ran for 4 min 54 sec  Total time 17 min 7 sec||

**Pull request merged**
