### PR TITLE
Un-pin requirements for installation

### LINKED ISSUE #581: Don't pin versions in setup.py
See #580

### PR DESCRIPTION
**Pull request by MinchinWeb**
Closes #581 

This is done (generally) by changing the currently required version to the minimum required version.

Hope this proves helpful!

### CODE REVIEW

**Comment by ttmc** [comment]
Hi @MinchinWeb 

Before we can merge this pull request, which may contain your intellectual property in the form of copyright or patents, our lawyers say we need you or your organization to agree to one of our contributor agreements. If you are contributing on behalf of yourself (and not on behalf of your employer or another organization you are part of) then you should:

1. Go to: https://www.bigchaindb.com/cla/
2. Read the Individual Contributor Agreement
3. Fill in the form "For Individuals"
4. Check the box to agree
5. Click the SEND button

If you're contributing as an employee, and/or you want all employees of your employing organization to be covered by our contributor agreement, then someone in your organization with the authority to enter agreements on behalf of all employees must do the following:

1. Go to: https://www.bigchaindb.com/cla/
2. Read the Entity Contributor Agreement
3. Fill in the form "For Organizations”
4. Check the box to agree
5. Click the SEND button

We will email you (or your employer) with further instructions.

**Comment by MinchinWeb** [comment]
Done.

But the CLA seems like a pretty big barrier to getting people involved. If you insist on have one (or your lawyers do), as a minimum, it would be good to add an explanation about why you want it signed, and, more importantly, what it does for me.

**Comment by gmcmullen** [comment]
Hi MinchinWeb, I'm the lawyer who is insisting on a CLA. Thanks for signing, and more importantly, for contributing. You're right - we should be clearer about why we need it. We'll be adding something like this:

> One of the big concerns for people using and developing open source software is that someone who contributed to the code might claim the code infringes on their copyright or patent. To guard against this, we ask all our contributors to sign a Contributor License Agreement. This gives us the right to use the code contributed and any patents the contribution relies on. It also gives us and our users comfort that they won’t be sued for using open source software. We know it’s a hassle, but it makes the project more reliable in the long run. Thank you for your understanding and your contribution!

**Comment by MinchinWeb** [comment]
BEGIN BLOCK

This is to confirm that I agreed to and accepted the BigchainDB Individual Contributor Agreement at https://www.bigchaindb.com/cla/ and to represent and warrant that I have authority to do so.

AuLRcLogw3PPUe5B7lq7PYMMVzvQiNMeRb8X572B1Nb2N2y8W2GDDLymJRmgbOu

END BLOCK

**Comment by MinchinWeb** [comment]
Hey Greg. Thanks for the added explanation. I think that makes in read a lot friendlier now!

**Comment by ttmc** [comment]
@MinchinWeb has agreed to the CLA and so that's no longer a blocker to merging this pull request.

**Comment by sbellem** [comment]
@MinchinWeb thanks for your help! Sorry for not processing your PR more promptly. The code has changed a bit in the meantime, such that your PR needs to be rebased against the latest master. Would you mind rebasing your work?

**Comment by MinchinWeb** [comment]
@sbellem: I see you have been busy! The PR has been rebased to the current master, plus I removed `bigchaindb-common` and `pytz` from the requirements.

I see one of the testing requirements (`pytest-cov`) was still pinned, so I unpinned that.

I also notices that `sphinxcontrib-napoleon` was listing as a doc requirement. Since Sphinx 1.3 (which is the minimum required version specified), this has actually shipped as part of the core as `sphinx.ext.napoleon`, so I've updated the requirement list and Sphinx configuration accordingly.

**Comment by sbellem** [comment]
Thanks @MinchinWeb !

**Comment by ttmc** [comment]
@MinchinWeb  Thanks for removing `pytz` and resolving issue #775 with this pull request as well!

**Pull request merged**
