### PR TITLE
aws monitor deployment

### PR DESCRIPTION
**Pull request by rhsimplex**
update docker-compose-monitor.yml, untested

### CODE REVIEW

**Comment by r-marques** [comment]
thanks. I will test this

**Comment by ttmc** [comment]
When I saw the title of this pull request, I thought maybe it was `codecov.yml` that got fixed.

**Comment by vrde** [comment]
This is in some ways connected to #224. @rhsimplex it's fine if we work together on this?

**Comment by r-marques** [comment]
@vrde I am actually working on this.

Mostly the part with deploying to aws. If you have any suggestions for the docker-compose we can work on that.

**Comment by rhsimplex** [comment]
@vrde @r-marques yes happy to help now that we're Docker Pros(TM)

**Comment by r-marques** [comment]
This pull request adds a way to set a docker volume for influxdb by setting the `INFLUXDB_DATA` env

```text
$ INFLUXDB_DATA=/influxdb-data docker-compose -f docker-compose-monitor up
```

Also created `fabfile-monitor` to install docker and run the monitor on a ec2 instance

**Comment by ttmc** [comment]
I checked this branch out on my machine; I'm testing it plus editing the docs right now. I'll push my changes back to this branch/PR when I get that done.

**Comment by ttmc** [comment]
I deployed a monitoring server according to the new docs, and edited the docs to add more details. It all worked fine as far as I could tell, but I will have to do more testing.

I pushed my changes to this branch/PR.

@r-marques Maybe review the edited docs and if you're okay with them, maybe we can merge this PR.

**Comment by r-marques** [comment]
@ttmc looks good :+1:

**Pull request merged**
