### PR TITLE
moved version number inside the transaction object

### PR DESCRIPTION
**Pull request by eladve**
As per #341

moved the transaction version (currently fixed to 1) from the outer
"transaction" object to the inside part, where it will get hashed
together with the rest of the transaction.

updated docs and tests accordingly.

Note that this feature might cause backwards incompatibility.

### CODE REVIEW

**Comment by ttmc** [comment]
Hi @eladve 

Before we can merge this pull request, which may contain your intellectual property in the form of copyright or patents, our lawyers say we need you or your organization to agree to one of our contributor agreements. If you are contributing on behalf of yourself (and not on behalf of your employer or another organization you are part of) then you should:

1. Go to: https://www.bigchaindb.com/cla/
2. Read the Individual Contributor Agreement
3. Fill in the form "For Individuals"
4. Check the box to agree
5. Click the SEND button

If you're contributing as an employee, and/or you want all employees of your employing organization to be covered by our contributor agreement, then someone in your organization with the authority to enter agreements on behalf of all employees must do the following:

1. Go to: https://www.bigchaindb.com/cla/
2. Read the Entity Contributor Agreement
3. Fill in the form "For Organizations”
4. Check the box to agree
5. Click the SEND button

We will email you (or your employer) with further instructions.

P.S. We generally don't make changes to the master branch directly. For details, see https://github.com/bigchaindb/bigchaindb/blob/master/CONTRIBUTING.md

**Comment by eladve** [comment]
@ttmc Perfect, I signed the CLI.

Should I do anything about pushing to the sub-branch? That's what I thought I was doing, but I'm used to Mercurial.

**Comment by ttmc** [comment]
There's nothing that can be done about the branch (`eladve:master`) that this pull request requests to be merged into `bigchaindb:master`. In future pull requests, you can create a new branch on your local machine, rather than committing direct to master.

**Comment by vrde** [comment]
@eladve thanks for your PR! Looks good to me.

**Comment by diminator** [comment]
looks good to me!
:+1:

**Comment by eladve** [comment]
This is to confirm that I agreed to and accepted the BigchainDB Individual Contributor Agreement at https://www.bigchaindb.com/cla/ and to represent and warrant that I have authority to do so.

Iy1GPDhX8uRi52pLjeurHqyzNJX0l7wxcjE4P2wFRDlKfpWZodk5MGilgpqXSAr

**Pull request merged**
