### PR TITLE
ensure timestamp is since epoch in UTC

### PR DESCRIPTION
**Pull request by diminator**
the `mktime` used local time not UTC, hence times weren't in global UTC

### CODE REVIEW

**Comment by r-marques** [comment]
:+1:

**Comment by ttmc** [comment]
Apparently `time.time()` [is timezone-independent](http://stackoverflow.com/questions/11845803/is-pythons-time-time-timezone-specific). Good!

However, from [the Python 3.4 docs for `time.time()`](https://docs.python.org/3.4/library/time.html#time.time):

> Return the time in seconds since the epoch as a floating point number. Note that even though the time is always returned as a floating point number, not all systems provide time with a better precision than 1 second.

I suggest that we also use this PR to round the timestamps off to the nearest second, since that's all the precision they have anyway.

**Comment by diminator** [comment]
> I suggest that we also use this PR to round the timestamps off to the nearest second, since that's all the precision they have anyway.

@r-marques @ttmc for me that's ok, :+1: for rounding to nearest second?

**Comment by diminator** [comment]
> I suggest that we also use this PR to round the timestamps off to the nearest second, since that's all the precision they have anyway.

@r-marques @ttmc any idea if there is a `format()` expression to `round` (and not only `floor` or `ceil`)?

**Comment by ttmc** [comment]
I looked around but even if there is one, I think we'd end up with easier-to-understand code if we just use a proper rounding function, rather than some fancy-pants, impossible-to-read expression for `format()`.

**Comment by diminator** [comment]
> I suggest that we also use this PR to round the timestamps off to the nearest second, since that's all the precision they have anyway.

It seems that rounding the `timestamp` will yield duplicate transaction hashes, which are rejected.
In order to do this properly we could change the `payload.hash` by `payload.uuid`

I suggest to do this rounding in another issue?

**Comment by r-marques** [comment]
closing this pull request in favor of #384

**Pull request closed without merging**
