### PR TITLE
RethinkDB User Accounts

### PR DESCRIPTION
**Pull request by saschad**

### CODE REVIEW

**Comment by r-marques** [comment]
Besides the drivers we also need to check or docker files and documentation and make sure to state that this only works with rethinkdb 2.3+

**Comment by r-marques** [comment]
Also need to check how this fits in the federation model. Who can and cannot create user accounts? Is there an admin/master account? If so we need to rethink (no pun intended) how to handle permissions

**Comment by ttmc** [comment]
Hi @saschad --- I see that you already signed the BigchainDB Individual Contributor Agreement: I got the email. I sent you an email reply explaining the next step. You'll have to do that before we can merge your pull requests.

Over on PR #153, @vrde is making some changes to how configuration works, so he'll probably also have some comments.

**Comment by saschad** [comment]
BEGIN BLOCK

This is to confirm that I agreed to and accepted the BigchainDB Individual Contributor Agreement at https://www.bigchaindb.com/cla/ and to represent and warrant that I have authority to do so.

tK11CNNGZymlN3ZACvgnYfVewUQvPMjQaN1XgruIPHQH3HerpfEqSo3XHeTWWAR

END BLOCK

**Comment by ttmc** [comment]
@saschad User accounts and related issues are something on our roadmap, but we need to discuss and think about them more first. BigchainDB is a non-standard system because it's supposed to be decentralized.

Therefore I'm going to close this pull request for now. I created an issue #177 where we can discuss these matters further.

**Pull request closed without merging**
