### PR TITLE
Bug/1337/init timeout rethinkdb conn

### PR DESCRIPTION
**Pull request by tdsgit**
fix for timeout not initialized on rethinkdb connection - issue 1337

### CODE REVIEW

**Comment by ttmc** [comment]
@tdsgit Thanks for tackling issue #1337 

I got an email when you agreed to the BigchainDB Contributor License Agreement. I will email you with instructions to finish that process by copying a block of text here.

**Comment by ttmc** [comment]
1. The test named `test_reconnect_when_connection_lost_tries_n_times` is failing when testing with the RethinkDB backend.
2. Please edit the docs page in the file `/docs/server/source/server-reference/configuration.md`. You can delete the sentence, "Note: At the time of writing, this setting was only used by MongoDB; there was an open issue to make RethinkDB use it as well." (It's referring to the `database.connection_timeout` setting and issue #1337.)

**Comment by tdsgit** [comment]
This is to confirm that I agreed to and accepted the BigchainDB Individual Contributor Agreement at https://www.bigchaindb.com/cla/ and to represent and warrant that I have authority to do so.

lytsOGTWWuBW0dNPVIfCe48ALgkLPgrlkmU6RUYHVDHlyZkMuNbFPoc4hmzNMCC

**Comment by ttmc** [comment]
Thanks @tdsgit - the CLA is no longer a blocker.

**Comment by vrde** [comment]
Hi @tdsgit, thanks for your PR. The `timeout` can be handled directly by the RethinkDB Driver:
 - https://rethinkdb.com/api/python/connect/

By passing the `timeout` parameter to the driver, you can also simplify a lot the code.

**Comment by tdsgit** [comment]
@vrde 
mongodb has pymongo driver which uses connection_timeout to wait/retry till timeout.
`bigchaindb -y configure mongodb`
`bigchaindb show-config`

the timeout when passed to rethinkdb driver directly was not waiting/retrying till timeout . it immediately exits if connection fails.
`>>> import rethinkdb as r`
`>>> r.connect("localhost",port,timeout=x)`

rethinkdb too has a default connection_timeout parameter similar to mongodb.
`bigchaindb -y configure rethinkdb`
`bigchaindb show-config`

hence the change

**Comment by vrde** [comment]
@tdsgit said:
> the timeout when passed to rethinkdb driver directly was not waiting/retrying till timeout . it immediately exits if connection fails.

When connecting to a socket, you can have those two errors:
- **connection error**: when the socket cannot be open because the target host is actively refusing the connection
- **timeout error** when:
  - the connection is established but the requested operation (e.g. a connection to the database) is not accomplished within the `timeout` time frame; or
  - the target host is dropping your packets.

If RethinkDB **is not** running and you try to connect, you'll get a `ReqlDriverError`. You can simulate this by **not** running RethinkDB on your machine, and trying to connect to localhost.

If RethinkDB **is** running but it is super slow in establishing the connection (it takes more than the predefined `timeout`), you'll get a `ReqlTimeoutError`. You can simulate this by running `nc -l 28015` on your machine, and trying to connect to localhost.

For the use case of #1337: connection refused and connection timeout should lead to a retry (note that this is handled already by [`bigchaindb.backend.connection.Connection::connect`](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/backend/connection.py#L130)).

The steps to achieve that are changing the module `bigchaindb.backend.rethinkdb.connection` and:
1. add the `timeout` parameter to `r.connect` [here](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/backend/rethinkdb/connection.py#L43)
2. add a new `except` to handle the `ReqlTimeoutError` [here](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/backend/rethinkdb/connection.py#L44)
3. (ideally, but we can take care of that) add a unit test for the timeout

**Comment by tdsgit** [comment]
@vrde wrote:

> add the timeout parameter to r.connect here

have mentioned adding timeout as extra argument in call from bigchaindb [issue](https://github.com/bigchaindb/bigchaindb/issues/1337#issuecomment-295727770) and mentioned the consequences
>however in rethinkdb the parameter to be passed is timeout ( not connection_timeout)
>r.connect(host=self.host, port=self.port, db=self.dbname, timeout=5000 )
>mock_connect.assert_called_once_with may assert
>original_connect also should pass timeout

later realized there was a iteration error from test_reconnect_when_connection_lost_tries_n_times and so on. 
moreover the main issue is rethinkdb driver is not honouring timeout when **DB is not running** which is already quoted in above comment (code inside **python prompt**). its only applicable for second test case `nc -l 28015`.
mongodb waits for timeout even when DB is not running i.e for both test cases.

@vrde wrote:

>add a new except to handle the ReqlTimeoutError here

this can be added as

`except (r.ReqlDriverError,r.ReqlTimeoutError) as exc:`

**Comment by vrde** [comment]
The problem with your solution is that you are trying to connect multiple times in a tight loop. The reconnection logic is handled by the super class [`bigchaindb.backend.connection.Connection`](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/backend/connection.py#L139). A solution would be to add a `time.sleep` if the connection fails, and then raise the exception. Please tell me if you have other ideas on how to solve this.

**Comment by tdsgit** [comment]
@vrde 

agree with sleep. have added .

**Comment by vrde** [comment]
Hi, sorry for my late reply. This implementation is still not compatible to the current behavior of the super class [`bigchaindb.backend.connection.Connection`](https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/backend/connection.py#L139). The `connect` method is the one that is responsible to retry. In your implementation if the first connection fails, there is anyway a second attempt.

I don't understand the `if str(exc) == 'mock'` in the exception handling, but I assume it's something related to the test suite we have. If that's the case, I bet [`unittest.mock`](https://docs.python.org/3/library/unittest.mock.html) has something we can use to avoid putting this statement in the code base.

I'm pretty busy with another project at the moment, I'll try to push some code on this PR soon.

**Comment by tdsgit** [comment]
@vrde 
`connect` leads to `_connect` which then leads to `rethinkdb.connect` 
the issue is not with bigchaindb implementation but with the rethinkdb driver which does not take timeout into account. have explained it in my previous comment. although have added, `r.ReqlTimeoutError` is not thrown currently by rethinkdb driver.

as far as mock is concerned, exception message is thrown by mocktests during testing.

**Comment by r-marques** [comment]
closed in favour of #1512

**Pull request closed without merging**
