### PR TITLE
check output conditions with single statement (#1450 unrevert)

### PR DESCRIPTION
**Pull request by diminator**
`GET /outputs` fails for specific transactions with thresholds

Invoked on the fastquery branch - but probably also on current master

## Stacktrace

```
  File "/home/dimi/code_ascribe/kyber/bigchaindb-server/bigchaindb/web/views/outputs.py", line 26, in ge
t                                                                                                       
    include_spent)                                                                                      
  File "/home/dimi/code_ascribe/kyber/bigchaindb-server/bigchaindb/core.py", line 400, in get_outputs_fi
ltered                                                                                                  
    outputs = self.fastquery.get_outputs_by_pubkey(owner)                                               
  File "/home/dimi/code_ascribe/kyber/bigchaindb-server/bigchaindb/fastquery.py", line 45, in get_output
s_by_pubkey                                                                                             
    for tx in txs                                                                                       
  File "/home/dimi/code_ascribe/kyber/bigchaindb-server/bigchaindb/fastquery.py", line 47, in <listcomp>
    if output_has_owner(o, pubkey)]                                                                     
  File "/home/dimi/code_ascribe/kyber/bigchaindb-server/bigchaindb/utils.py", line 125, in output_has_ow
ner                                                                                                     
    return output['condition']['details']['public_key'] == owner                                        
KeyError: 'public_key'                                                                                  
```

## Testvector

```json
{
  "inputs": [
    {
      "fulfills": null,
      "fulfillment": "cf:4:W0dEBH4MFkphXyUzeuY04q8z2visobk5dtiggDfGdOeEzY975pWXZ-nIUHHZ-XDKHha-hiWFs-ido88fPS_fCOmskfpbaB_-yhkVGlc-bdx6irzpD6fWkuRHoe5V0usH",
      "owners_before": [
        "79K8SPZbeSDYXBrWgt3dsNmYTZbKNtdYQ5XrjA9XEWfG"
      ]
    }
  ],
  "id": "c6de675dfef4411c37c2adef80c8ece82740fb48f991613f3d8222029297e3a7",
  "asset": {
    "data": {
      "frequency": 5,
      "timestamp": "1493639461",
      "item": "shirt"
    }
  },
  "operation": "CREATE",
  "metadata": null,
  "outputs": [
    {
      "public_keys": [
        "79K8SPZbeSDYXBrWgt3dsNmYTZbKNtdYQ5XrjA9XEWfG"
      ],
      "amount": "1",
      "condition": {
        "details": {
          "subfulfillments": [
            {
              "signature": null,
              "public_key": "79K8SPZbeSDYXBrWgt3dsNmYTZbKNtdYQ5XrjA9XEWfG",
              "weight": 1,
              "type_id": 4,
              "type": "fulfillment",
              "bitmask": 32
            },
            {
              "subfulfillments": [
                {
                  "hash": "5wbD6GsVBReHetMUw17QcNne8BjB1xSKRoU4JYpafEx5",
                  "type_id": 0,
                  "weight": 1,
                  "max_fulfillment_length": 5,
                  "type": "condition",
                  "bitmask": 3
                },
                {
                  "hash": "EuNEkS8TUYaTngMPGiS3DHdApYBf2YYQVdg3hHHTnPDx",
                  "type_id": 0,
                  "weight": 1,
                  "max_fulfillment_length": 11,
                  "type": "condition",
                  "bitmask": 3
                },
                {
                  "hash": "Ay3VvUjfEnEhCWxJMGLGBpWTS5iu2nVB64wcsYkPnCqd",
                  "type_id": 0,
                  "weight": 1,
                  "max_fulfillment_length": 5,
                  "type": "condition",
                  "bitmask": 3
                },
                {
                  "hash": "H7nD6xkFRm99GzAxvA5JG8DQSZBEGdiUdnYuh7714vMW",
                  "type_id": 0,
                  "weight": 1,
                  "max_fulfillment_length": 10,
                  "type": "condition",
                  "bitmask": 3
                },
                {
                  "hash": "8EmZwLhhFAZ9QgHgHfgMokfQ2CfzXaLbyEz4uaXaJyq4",
                  "type_id": 0,
                  "weight": 1,
                  "max_fulfillment_length": 7,
                  "type": "condition",
                  "bitmask": 3
                },
                {
                  "hash": "DFf8KSmzgHEarJ2RPJmyDGTvnS8E8MjxkDNVjNsUN8Hr",
                  "type_id": 0,
                  "weight": 1,
                  "max_fulfillment_length": 8,
                  "type": "condition",
                  "bitmask": 3
                },
                {
                  "hash": "3qUBtEhzGazLRTM9c3JWKGPTnrkgxbtEoezh7WaJuJBS",
                  "type_id": 0,
                  "weight": 1,
                  "max_fulfillment_length": 3,
                  "type": "condition",
                  "bitmask": 3
                },
                {
                  "hash": "4w6YMt6nH3oSsA1uTk6Vmqvqsa9eSquKSAxWtDWPrzTg",
                  "type_id": 0,
                  "weight": 1,
                  "max_fulfillment_length": 4,
                  "type": "condition",
                  "bitmask": 3
                }
              ],
              "weight": 1,
              "type_id": 2,
              "type": "fulfillment",
              "bitmask": 11,
              "threshold": 3
            }
          ],
          "type_id": 2,
          "type": "fulfillment",
          "bitmask": 43,
          "threshold": 2
        },
        "uri": "cc:2:2b:VC7Jv-cUz8xcnSSR11K4nGe0myDWrmOaf3LFfwYPOwQ:358"
      }
    }
  ],
  "version": "0.9"
}

```

## TODO

- [x] check why the statement for a single list item was there
- [ ] write test to reproduce stacktrace above with testvector
- [ ] @sbellem shim cryptoconditions-specific utils ie `condition_details_has_owner` (see also [CC utils in Kyber](https://github.com/bigchaindb/kyber/blob/master/tutorials/utils/cryptoconditions_utils.py))

### CODE REVIEW

**Comment by r-marques** [comment]
@diminator is this still a problem with the latest master?

**Comment by diminator** [comment]
No, It's still a problem...

https://github.com/bigchaindb/bigchaindb/blob/master/bigchaindb/utils.py#L117

**Comment by r-marques** [comment]
> check why the statement for a single list item was there

It was there to check if we needed to look for the public key in the condition details or in the subfulfillments in the case of threshold condition.

This is because we were not expecting hashlocks so a threshold condition would always have multiple public keys.

Also agree that `output_has_owner` does not need to make this check since `condition_details_has_owner` already takes care of all the cases.

**Comment by diminator** [comment]
ok, so how do we proceed?

merge as is or plan it further?

**Comment by TimDaub** [comment]
I assigned @r-marques and @libscott to take care of this for the upcoming QA week.

**Comment by r-marques** [comment]
The report bug is fixed.
I would just like to refactor the code a bit more since I found this issue #1367

**Comment by r-marques** [comment]
This also resolves #1367

**Pull request merged**
