### PR TITLE
Feat/151/deploy cluster on aws

### LINKED ISSUE #151: Scripts to deploy a cluster on AWS, including usage docs
Andreas already wrote some scripts (bash, Python, Fabric) to deploy a BigchainDB cluster on AWS, in a separate private repository. The goals of this issue are to:
- [x] move Andreas' code into a new subdirectory of this repository
- [x] make sure it still works: use it deploy a cluster on AWS
- [x] make sure no private keys will get pushed to the public GitHub repository (e.g. by putting private files in `.gitignore`)
- [x] rename variable, files and directories using "bigchain" to "bigchaindb"
- [x] switch from `boto` to `boto3` (AWS SDK for Python)
- [x] remove `awscli` stuff, if it's not actually used any more (as seems to be the case)
- [x] see if it's possible to stick to pure Python 2 (i.e. no `python3` invocations). (Pure Python 3 is not possible because Fabric doesn't work with Python 3 yet.)
- [x] clean up the Python code so it conforms better with our Python Style Guide
- [x] rename `conf/bigchaindb.conf` to `conf/rethinkdb.conf`
- [x] write documentation to explain the steps one must take to setup their environment, get the keys they need, and run the scripts

I started this a few days ago but Trent suggested I make an issue for it.

### PR DESCRIPTION
**Pull request by ttmc**
This PR brings scripts for deploying a cluster on AWS into the new `/deploy-cluster-aws` top-level subdirectory. Those scripts started out as the scripts that Andreas wrote in a private (ascribe) repository. I did some revisions, updating, and refactoring as described in Issue #151 and the commit messages.

I also added a new section to the docs, explaining how to use the scripts.

Resolves #151

### CODE REVIEW

**Comment by ttmc** [comment]
As noted in the new section of the documentation:

> NOTE: At the time of writing, these script _do_ launch a bunch of EC2 instances, and they do install RethinkDB plus BigchainDB on each instance, but don't expect to be able to use the cluster for anything useful. There are several issues related to configuration, networking, and external clients that must be sorted out first. That said, you might find it useful to try out the AWS deployment scripts, because setting up to use them, and using them, will be very similar once those issues get sorted out.

**Comment by rhsimplex** [comment]
https://github.com/bigchaindb/bigchaindb/edit/feat/151/deploy-cluster-on-AWS/docs/source/deploy-on-aws.md#L18-23 could be rewritten to one line

```bash
pip install fabric fabtools requests boto3
```

**Comment by ttmc** [comment]
Okay @rhsimplex I changed the pip installs to a one-liner as suggested.

**Comment by rhsimplex** [comment]
Ok a few problems:

When I get everything running more or less as described:

```bash
ryan@ryan: deploy-cluster-aws (feat/151/deploy-cluster-on-AWS) $ ./startup.sh wrigley 4
Checking if you have enough allocated-but-unassociated EC2 elastic IP addresses...
You have 0 allocated elactic IPs which are not already associated with instances
You want to launch 4 instances
so 4 more elastic IPs must be allocated
Commencing launch of 4 instances on Amazon EC2...
The launched instances will have these ids:
i-0d37aab1
i-0337aabf
i-a931ac15
i-0237aabe
Waiting until all those instances exist...
Waiting until all those instances are running...
Associating allocated-but-unassociated elastic IPs with the instances...
Grabbing an allocated but non-associated elastic IP...
The public IP address 52.58.107.73
was associated with the instance with id i-0d37aab1
Grabbing an allocated but non-associated elastic IP...
The public IP address 52.28.234.247
was associated with the instance with id i-0337aabf
Grabbing an allocated but non-associated elastic IP...
The public IP address 52.58.101.197
was associated with the instance with id i-a931ac15
Grabbing an allocated but non-associated elastic IP...
The public IP address 52.29.179.165
was associated with the instance with id i-0237aabe
Preparing shellscript to add remote keys to known_hosts
Writing hostlist.py
Waiting 45 seconds to make sure all instances are ready...
# ec2-52-58-107-73.eu-central-1.compute.amazonaws.com:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
# ec2-52-58-107-73.eu-central-1.compute.amazonaws.com:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
# ec2-52-58-107-73.eu-central-1.compute.amazonaws.com:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
# ec2-52-28-234-247.eu-central-1.compute.amazonaws.com:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
# ec2-52-28-234-247.eu-central-1.compute.amazonaws.com:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
# ec2-52-28-234-247.eu-central-1.compute.amazonaws.com:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
# ec2-52-58-101-197.eu-central-1.compute.amazonaws.com:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
# ec2-52-58-101-197.eu-central-1.compute.amazonaws.com:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
# ec2-52-58-101-197.eu-central-1.compute.amazonaws.com:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
# ec2-52-29-179-165.eu-central-1.compute.amazonaws.com:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
# ec2-52-29-179-165.eu-central-1.compute.amazonaws.com:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
# ec2-52-29-179-165.eu-central-1.compute.amazonaws.com:22 SSH-2.0-OpenSSH_6.6.1p1 Ubuntu-2ubuntu2
Traceback (most recent call last):
  File "/home/ryan/bigchaindb/env/bin/fab", line 9, in <module>
    load_entry_point('Fabric==1.10.2', 'console_scripts', 'fab')()
  File "/home/ryan/bigchaindb/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/ryan/bigchaindb/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2542, in load_entry_point
    return ep.load()
  File "/home/ryan/bigchaindb/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2202, in load
    return self.resolve()
  File "/home/ryan/bigchaindb/env/lib/python3.4/site-packages/pkg_resources/__init__.py", line 2208, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/ryan/bigchaindb/env/lib/python3.4/site-packages/fabric/main.py", line 12, in <module>
    from operator import isMappingType
ImportError: cannot import name 'isMappingType'
```

I don't know if this worked or not. The instances start and don't terminate, so maybe? Tried to ssh into one, no dice:

```bash
(env)ryan@ryan: deploy-cluster-aws (feat/151/deploy-cluster-on-AWS) $ chmod 400 pem/bigchaindb.pem 
(env)ryan@ryan: deploy-cluster-aws (feat/151/deploy-cluster-on-AWS) $ ssh -i pem/bigchaindb.pem ubuntu@ec2-52-28-234-247.eu-central-1.compute.amazonaws.com
Permission denied (publickey).
```

These scripts also seem to access the environment variables directly, which interferes with aws-CLI apparently and causes weird behavior.  The recommended way of setting up AWS is:

```bash
ryan@ryan: deploy-cluster-aws (feat/151/deploy-cluster-on-AWS) $ aws configure
AWS Access Key ID [****************JK5A]: 
AWS Secret Access Key [****************Nx/f]: 
Default region name [eu-central-1]: 
Default output format [None]: 
```

But when you do this you get a private key error. Using the export commands works. Let me know if I can help.

**Comment by rhsimplex** [comment]
ok python3 i am dumb

**Comment by rhsimplex** [comment]
Works as you was =) one thing to remember: relaunching with the same tag immediately can cause problems, since it sees the tags of the terminated instances.

**Comment by ttmc** [comment]
Based on Ryan's tests yesterday, it became clear that there are some simple improvements that can be made before merging this PR:

- [ ] Use the more standard AWS credentials file (`~/.aws/credentials`) to store AWS key id and value, rather than using environment variables. Update the docs accordingly.
- [ ] Get users to set their default AWS region name in `~/.aws/config` rather than in an environment variable.
- [ ] Allow users to name their new AWS key pair whatever they like (not just bigchaindb). Have them put that name in `awscommon.py`
- [ ] Allow users to name their new AWS security group whatever they like (not just bigchaindb). Have them put that name in `awscommon.py`
- [ ] When they run `startup.sh`, start by checking if they already have any instances with the specified tag (in any state). If so, raise an error explaining why that can cause problems, and tell them to use a different tag.
- [ ] In the documentation, after they've got a cluster running, show examples of how to `ssh` into a node, check things are running, and connect to the RethinkDB web interface.

**Comment by r-marques** [comment]
> `pip install fabric fabtools requests boto3`

Is boto3 a new version of boto or boto for python3? Note that fabric does not work under python3

**Comment by ttmc** [comment]
boto3 is a new version of boto that works with Python 2 and Python 3, but we use it with Python 2 because Fabric only works with Python 2.

**Pull request merged**
