### PR TITLE
Problem: docs are not building anymore

### PR DESCRIPTION
**Pull request by codegeschrei**
Solution: add wget to the requirements for docs

### CODE REVIEW

**Comment by ldmberman** [comment]
@muawiakh @shahbazn looks like documentation builds started to fail after the base Docker image was updated (wget was excluded). Should we fix the image versions that we are using to avoid such incidents?

**Comment by muawiakh** [comment]
I am not entirely sure when it was removed, also I don't entirely understand by what you mean by fix image versions that we are using? Installing as part of the docker image would be the ideal scenario IMO, not in the `setup.py`

**Comment by codegeschrei** [comment]
oh, if that's the case I can change it

**Comment by ldmberman** [comment]
> what you mean by fix image versions that we are using

I mean, in the `Dockerfile` put `FROM <os>:<paricular-version>`.

**Comment by shahbazn** [comment]
>Installing wget inside the docker image would be the ideal scenario IMO, not in the setup.py
Agreed

**Comment by codegeschrei** [comment]
We have the `wget` requirement in [here](https://github.com/bigchaindb/bigchaindb/blob/master/docs/contributing/requirements.txt) 
In all `docs` folders we have different requirements, which are also in `setup.py` except for the wget. So to me it makes sense to just add it to the `setup.py` instead of `Dockerfile`

**Comment by shahbazn** [comment]
@ldmberman possible that `wget` installed as part of the image by default before i am not sure how it got broken. will merge this now

**Pull request merged**
