### PR TITLE
Bug-437 Pretty message when drop nonexistent db

### LINKED ISSUE #437: bigchaindb drop raises exception if database does not exist
If the bigchain database does not exist, running `bigchaindb drop` raises and exception:

``` bash
$ bigchaindb drop
INFO:bigchaindb.config_utils:Configuration loaded from `/home/rodmar/.bigchaindb`
Do you want to drop `bigchain` database? [y/n]: y
INFO:bigchaindb.db.utils:Drop database `bigchain`
Traceback (most recent call last):
  File "/home/rodmar/code/code-ascribe/bigchaindb/bigchaindb/db/utils.py", line 88, in drop
    r.db_drop(dbname).run(conn)
  File "/home/rodmar/.venvs/bigchaindb/lib/python3.4/site-packages/rethinkdb/ast.py", line 118, in run
    return c._start(self, **global_optargs)
  File "/home/rodmar/.venvs/bigchaindb/lib/python3.4/site-packages/rethinkdb/net.py", line 625, in _start
    return self._instance.run_query(q, global_optargs.get('noreply', False))
  File "/home/rodmar/.venvs/bigchaindb/lib/python3.4/site-packages/rethinkdb/net.py", line 468, in run_query
    raise res.make_error(query)
rethinkdb.errors.ReqlOpFailedError: Database `bigchain` does not exist in:
r.db_drop('bigchain')
^^^^^^^^^^^^^^^^^^^^^

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rodmar/.venvs/bigchaindb/bin/bigchaindb", line 9, in <module>
    load_entry_point('BigchainDB', 'console_scripts', 'bigchaindb')()
  File "/home/rodmar/code/code-ascribe/bigchaindb/bigchaindb/commands/bigchain.py", line 306, in main
    utils.start(parser, globals())
  File "/home/rodmar/code/code-ascribe/bigchaindb/bigchaindb/commands/utils.py", line 95, in start
    func(args)
  File "/home/rodmar/code/code-ascribe/bigchaindb/bigchaindb/commands/bigchain.py", line 149, in run_drop
    db.drop(assume_yes=args.yes)
  File "/home/rodmar/code/code-ascribe/bigchaindb/bigchaindb/db/utils.py", line 91, in drop
    raise exceptions.DatabaseDoesNotExist('Database `{}` does not exist'.format(dbname))
bigchaindb.exceptions.DatabaseDoesNotExist: Database `bigchain` does not exist
```

The exception should be catched and a message printed the same way that when running `bigchaindb init` and the database already exists:

``` bash
$ bigchaindb init
INFO:bigchaindb.config_utils:Configuration loaded from `/home/rodmar/.bigchaindb`
The database already exists.
If you wish to re-initialize it, first drop it.
```

### PR DESCRIPTION
**Pull request by anujism**
An except clause is added to print a human readable pretty error message if 'drop' command is called for a non-existent database.

resolves #437

### CODE REVIEW

**Comment by ttmc** [comment]
Thanks @anujism 

I sent you an email with the next (and last) step in the process to agree to the Contributor License Agreement (CLA).

**Comment by anujism** [comment]
BEGIN BLOCK

This is to confirm that I agreed to and accepted the BigchainDB Individual Contributor Agreement at https://www.bigchaindb.com/cla/ and to represent and warrant that I have authority to do so.

7G2Ar04pzDuOJ2xhgrnnNcRpmH0VJGDM0W1qbREpVgh9yGFyKGoYJXkDs1KipCj

END BLOCK

**Comment by ttmc** [comment]
Thanks! The CLA hurdle is passed.

I requested @r-marques as a reviewer because he created the issue (#437) which this pull request resolves.

**Comment by r-marques** [comment]
@anujism everything looks perfect.
The only think remaining is syncing this with master to resolve the conflicts so that we can merge.

**Comment by anujism** [comment]
Ok. I will resolve the conflicts and commit.

**Comment by anujism** [comment]
@r-marques I have merged and resolved the conflicts. Please merge into master.

**Comment by r-marques** [comment]
👍

**Pull request merged**
