### PR TITLE
Added notes about support for hashlock & timeout conditions

### PR DESCRIPTION
**Pull request by ttmc**
A minor update to the docs to keep them current.

### CODE REVIEW

**Comment by TimDaub** [comment]
What's being updated here is not correct.

All conditions and fulfillments provided by bigchaindb/cryptoconditions are fully supported by both the core as well as the Transaction model.

How?

Create a `Transaction()`.
Use `Transaction.add_condition` and `Transaction.add_fulfillment`.
Sign. Serialize, Push it to the server.

The only thing that's currently missing is documentation.

**Comment by ttmc** [comment]
Okay, I'll close this PR. I'm pretty sure Sylvain will be documenting some of how to use the Python driver to work with hashlock and timeout conditions, because some of the Advanced Usage examples involve those.

**Comment by sohkai** [comment]
@TimDaub but https://github.com/bigchaindb/bigchaindb/issues/836 was made to remove support for hashlocks? If we've already gone down this road, I think we should be providing some warning signs.

Also, I'm not sure anybody can actually use `add_condition` or `add_fulfillment` since the driver (AFAIK) doesn't expose the transaction model in a way that someone could use it like that.

**Comment by TimDaub** [comment]
That's the problem of the driver (or the driver's docs) not the node's documentation.

**Pull request closed without merging**
