### PR TITLE
owners_before error message correction

### LINKED ISSUE #2697: Wrong error message on owners_before not being a list
**Describe the bug**
When we are trying to transfer an asset, the driver/common/transaction.py file throws an error if the "owners_before" is not a list instance it throws an error with the message : TypeError: `owners_after` must be a list instance. The message should point to the right variable

**To Reproduce**
Try transferring an asset with owners_before being a string rather than a list

**Expected behavior**
The error message should say: TypeError: `owners_before` must be a list instance.

**Logs or terminal output**
If applicable, add add textual content to help explain your problem.
site-packages/bigchaindb_driver/common/transaction.py", line 86, in __init__
    raise TypeError('`owners_after` must be a list instance')
TypeError: `owners_after` must be a list instance

**Desktop (please complete the following information):**
 - Distribution: Manjaro
- Python full version: Python 3.6.10

### PR DESCRIPTION
**Pull request by amartya-dev**
Make sure the title of this pull request has the form:

**Problem: A short statement of the problem.**
Wrong error message on owners_before not being an instance if a list

## Solution

A short statement about how this PR solves the **Problem**.

I have simply changed the error message to point in the right direction. The documentation containing basic usage examples might also be needed to change a little bit as any asset transfer needs owner_before as a list and in the documentation, a string of public key is supplied.

## Issues Resolved

What issues does this PR resolve, if any? Please include lines like the following (i.e. "Resolves #NNNN), so that when this PR gets merged, GitHub will automatically close those issues.

Resolves #2697 

## BEPs Implemented

What [BEPs](https://github.com/bigchaindb/beps) does this pull request implement, if any?

### CODE REVIEW

**Comment by zzappie** [comment]
Hi @amartya-dev!  Thanks for the fix.  There are couple problems with your pr...  It contains conflicts with master and commits are not signed off.  I can only merge your pr if you'll add sign off line to your commits.

**Comment by amartya-dev** [comment]
Ok I will see to that... Thanks @zzappie

**Comment by amartya-dev** [comment]
@zzappie I have made the required changes please see to them.

**Comment by zzappie** [comment]
Hi @amartya-dev. Sorry about late response. As I mentioned above I really need to make sure that commits are signed off.
This means that commits need to look like so
```
Added some changes

Signed-off-by: Your Name <name@example.org>
```
This is just for legal reasons... If this is too much fuss about one line change you could just close the pr and I'll add the fix anyways :)

**Comment by amartya-dev** [comment]
I would rather do it myself :P Changed the commit messages accordingly. Let me know if there is anything else needed.

**Comment by zzappie** [comment]
Great!

**Pull request merged**
