### PR TITLE
Feat/51/add CHANGELOG.md file

### PR DESCRIPTION
**Pull request by ttmc**
This PR resolves Issue #51 (Add a CHANGELOG.md file). I created a first draft of CHANGELOG.md.

It's probably missing some stuff. Please say if some _key_ feature or bugfix got missed.

This PR also makes related changes to CONTRIBUTING.md, ROADMAP.md, and the documentation (Release Notes section).

### CODE REVIEW

**Comment by r-marques** [comment]
It would be nice to also add a list of contributors in each release

**Comment by vrde** [comment]
> It would be nice to also add a list of contributors in each release

It's a good idea! We can find the contributors form in an interval of commits using `git shortlog -s -n <from>..<to>`

For example, this will output the contributors between `v0.1.4` and `develop`.
```
git shortlog -s -n v0.1.4..develop
```

**Comment by vrde** [comment]
Looks good to me, not sure if I'd include the instructions on how to handle the changelog in the `CHANGELOG.md` file itself, should we the instructions to the documentation? Any thoughts about that?

**Comment by r-marques** [comment]
nice. But we can probably omit `BigchainDB members` and only include in the changelog external contributors

**Comment by vrde** [comment]
> nice. But we can probably omit BigchainDB members and only include in the changelog external contributors

agree

**Comment by ttmc** [comment]
I think it's convenient to have the tips on CHANGELOG formatting in the CHANGELOG itself.

For listing contributors; I agree that it may be better to list external contributors. Does that mean "not employees of ascribe GmbH?"

**Comment by r-marques** [comment]
I guess all ascribe employees are also BigchainDB members.

I think is is good to be merged :+1:

**Pull request merged**
