### PR TITLE
delete superfluous decorator

### PR DESCRIPTION
**Pull request by lonelypeanut**
Deleted a duplicate pytest.fixture.

### CODE REVIEW

**Comment by ttmc** [comment]
Hi @lonelypeanut 

Before we can merge this pull request, which may contain your intellectual property in the form of copyright or patents, our lawyers say we need you or your organization to agree to one of our contributor agreements. If you are contributing on behalf of yourself (and not on behalf of your employer or another organization you are part of) then you should:

- Go to: https://www.bigchaindb.com/cla/
- Read the Individual Contributor Agreement
- Fill in the form "For Individuals"
- Check the box to agree
- Click the SEND button

If you're contributing as an employee, and/or you want all employees of your employing organization to be covered by our contributor agreement, then someone in your organization with the authority to enter agreements on behalf of all employees must do the following:

- Go to: https://www.bigchaindb.com/cla/
- Read the Entity Contributor Agreement
- Fill in the form "For Organizations”
- Check the box to agree
- Click the SEND button

We will email you (or your employer) with further instructions.

**Comment by lonelypeanut** [comment]
This is to confirm that I agreed to and accepted the BigchainDB Individual Contributor Agreement at https://www.bigchaindb.com/cla/ and to represent and warrant that I have authority to do so.

YM5Q1ILLCrMwlLyHobUsLhD2rgjguzz88GWAGdpDea6tblRIDdREIjOfAisBURz

**Comment by ttmc** [comment]
Thanks @lonelypeanut --- I'd like at least one other member of our team to look at this PR before we merge it. That will probably be on Monday.

**Comment by sbellem** [comment]
:+1: 

@ttmc @lonelypeanut is at the [EuroPython sprint](https://ep2016.europython.eu/en/events/sprints/) helping with the project!

**Pull request merged**
