### PR TITLE
Tymlez consensus plugin

### PR DESCRIPTION
**Pull request by libscott**
Own branch to test and address some small issues for Tymlez consensus plugin (#1108).

### CODE REVIEW

**Comment by ttmc** [comment]
Hi @tymlez 

Before we can merge this pull request, we need you or your organization to agree to one of our contributor agreements. One of the big concerns for people using and developing open source software is that someone who contributed to the code might claim the code infringes on their copyright or patent. To guard against this, we ask all our contributors to sign a Contributor License Agreement. This gives us the right to use the code contributed and any patents the contribution relies on. It also gives us and our users comfort that they won't be sued for using open source software. We know it's a hassle, but it makes the project more reliable in the long run. Thank you for your understanding and your contribution!

If you are contributing on behalf of yourself (and not on behalf of your employer or another organization you are part of) then you should:

1. Go to: https://www.bigchaindb.com/cla/
2. Read the Individual Contributor Agreement
3. Fill in the form "For Individuals"
4. Check the box to agree
5. Click the SEND button

If you're contributing as an employee, and/or you want all employees of your employing organization to be covered by our contributor agreement, then someone in your organization with the authority to enter agreements on behalf of all employees must do the following:

1. Go to: https://www.bigchaindb.com/cla/
2. Read the Entity Contributor Agreement
3. Fill in the form "For Organizations”
4. Check the box to agree
5. Click the SEND button

We will email you (or your employer) with further instructions.

**Comment by tymlez** [comment]
Done ☺

**Comment by ttmc** [comment]
@tymlez We sent you an email with a block of text (including a long secret code).

Before we can merge this pull request, you must copy that block of text into the comments below (on GitHub). That way we can be confident that you are the same person/organization who agreed to the CLA (and for whom we only have an email address at this point).

**Comment by tymlez** [comment]
This is to confirm that I agreed to and accepted the BigchainDB Organization (Entity) Contributor Agreement at https://www.bigchaindb.com/cla/ and to represent and warrant that I have authority to do so.

6K72JwcgbiEqXqT9tZueuf6sZkL9BfkfMQg9Nl5AE6tbejthymJrdxb5dZyexov

**Comment by tymlez** [comment]
Hi Troy,
He has just done it. Can u check that everything is ok ?

Cheers, Mike

**Comment by ttmc** [comment]
@tymlez Great, thanks!

@libscott All the steps to agree with the CLA are done now, so that's no longer a blocker to merging this pull request.

**Comment by tymlez** [comment]
Thx ☺

**Comment by libscott** [comment]
Great, merging then, thanks for this @tymlez.

**Pull request merged**
