### PR TITLE
Test templates

### PR DESCRIPTION
**Pull request by r-marques**
This pull requests adds some utils and templates for benchmark tests.

Added a folder `benchmarking-tests`. In the root of the folder there is a `fabfile.py` and `benchmark_utils.py`. This contains utilities common to all tests.

Inside `benchmarking-tests` there will be several test folders containing a `README` with the steps needed to reproduce the test and possibly custom scripts for that particular test.

### CODE REVIEW

**Comment by ttmc** [comment]
I made some minor changes to the names of commands and fabfile tasks, otherwise :+1:

**Comment by r-marques** [comment]
I just added a README file to the benchmarking-tests folder to explain what that folder is for.

**Comment by ttmc** [comment]
I'm going to add a bit more to `test1/README.md`. I will push that soon.

**Comment by ttmc** [comment]
Okay done.

**Pull request merged**
