### PR TITLE
Problem: Liveness probe too aggressive

### PR DESCRIPTION
**Pull request by muawiakh**

### CODE REVIEW

**Comment by shahbazn** [comment]
Whats the issue here caused by liveness probe being aggressive ?

**Comment by muawiakh** [comment]
Sometimes, failures are caused by network delays or tendermint recovers itself. So keeping it a bit laid back.

**Comment by ttmc** [comment]
I wanted to better-understand what `periodSeconds` means, so I looked it up. Apparently it is _how often_ the kubelet performs a liveness probe.

https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-probes/#configure-probes

`timeoutSeconds` is "Number of seconds after which the probe times out." Maybe we should be increasing that?

**Comment by muawiakh** [comment]
We already have a max timeout of 10 seconds here(https://github.com/bigchaindb/bigchaindb/blob/master/k8s/bigchaindb/bigchaindb-ss.yaml#L139), which should be sufficient because it is being resolved over `localhost`.  I am just changing the frequency of the the probe.

**Pull request merged**
