### PR TITLE
Feature multisig

### PR DESCRIPTION
**Pull request by diminator**
This PR overrules #106 (excludes unnecessary files)

The contribution of this fork is to implement n-of-n multisig.

Multisig allows a single `current_owner` to send an asset to multiple `new_owners`.
Moreover, once an asset has multiple `current_owners`, all `current_owners` need to sign the transaction before it validates to `True` on `validate_transaction()`

This PR replaces all occurances of `current_owner` and `new_owner` into `current_owners` and `new_owners`. These are lists of public keys but `create_transaction()` and `sign_transaction()` still supports single strings, not embedded in a list for the single case.

Upon signing a multisig one needs to provide his public key to identify who's signature is being added. Note that this is optional and can be omitted for the single case. For the multisig case, the signature takes the form of a list of dicts (the single case only renders a string, as before):

```
signatures = [
    {
        'public_key': ...,
        'signature': ....
    },
    ...
]
```

### CODE REVIEW

**Comment by r-marques** [comment]
Some code related to transactions moved in #102 pr.
Probably a good idea to merge that pr first and them review this one.

**Comment by thedoctor** [comment]
Is there a reason for the choice to implement `n-of-n` instead of `m-of-n`?

**Comment by r-marques** [comment]
Just for simplicity in a first iteration of multisig support we require a signature from all current owners of the digital asset

**Comment by diminator** [comment]
This is a subset of #147, so no longer required

**Pull request closed without merging**
