### PR TITLE
remove block update

### PR DESCRIPTION
**Pull request by rhsimplex**
old logic for handling updates to blocks, no longer needed now that votes are a separate table. this should have been part of #379 and makes sure #221 still works correctly

### CODE REVIEW

**Comment by r-marques** [comment]
:+1:

**Comment by rhsimplex** [comment]
@r-marques actually this was a little more involved than I thought. Thanks @vrde for catching this.

**Comment by r-marques** [comment]
good catch

**Comment by vrde** [comment]
Closing since we moved to _pipelines_.

**Pull request closed without merging**
