### PR TITLE
Move monitoring code from the main class to processes

### PR DESCRIPTION
**Pull request by vrde**
This PR is related to #156.

I might need some help from @rhsimplex to check if the new setup is compatible to the one we had before.

Note also we don't monitor `create_transaction` anymore, because this action will be done on the client side, not on the server side.

I moved `write_transaction` to the API server, because this is where the write happens. An idea for the future: we can add `statsd` on every API endpoint to measure how the HTTP Server behaves.

### CODE REVIEW

**Comment by rhsimplex** [comment]
Transaction Write Time/Rate are not showing up properly in the dashboard. I'll try to find specifically what the failure is.

**Comment by r-marques** [comment]
the code seems good :+1:

**Comment by vrde** [comment]
@rhsimplex moar tests, moar coverage. Everything should work fine now :ok_hand:.

**Comment by rhsimplex** [comment]
:+1:

**Comment by vrde** [comment]
@rhsimplex quick fix to remove the logging from `requests`.

**Pull request merged**
