### PR TITLE
Filter data with specific fields, linked assets with transactions

### LINKED ISSUE #1496: Consider storing block ids with the assets in the assets table
The assets are stored in the assets table with the `id` of the transaction that created the asset.
When querying the assets we first need to make sure that the `id` belongs to a valid transaction. This is inefficient.
A more efficient way would be to use the fastquery but we would need to store the block id with the asset.
The only problem with this approach is that we would possibly be storing the same asset multiple times when so blocks are voted invalid.

### PR DESCRIPTION
**Pull request by MisterDr**
## Description
Added new API endpoint for searching through assets with specific filter:
api/v1/assets/search?search={"COIN": "BTC"} will list all coins which contain BTC value.
Integrated block votes for every asset: 
Above mentioned query will return:
[{"data": {"COIN": "BTC"}, "id": "210f5c2be51311ac91e31bc9e9e3f02bf7845b68e857158c2e02a44ac425880a", "voters": 1}]

## Issues This PR Fixes
Fixes #1496 

## Todos
- [x] Tested and working on development environment
- [ ] Unit tests (if appropriate)
- [ ] Added/Updated all related documentation.
- [ ] DevOps Support needed e.g. create Runscope API test if new endpoint added or
      update deployment docs. Create a ticket and add [link]()

## Deployment Notes
Compile and test on the search API

## How to QA
Outline the steps to test or reproduce the PR here.
api/v1/assets/search?search={} with custom data filtering

## Impacted Areas in Application
List general components of the application that this PR will affect:
- Performance / much faster than full-text search, integrated block verification

This is to confirm that I agreed to and accepted the BigchainDB Individual Contributor Agreement at https://www.bigchaindb.com/cla/ and to represent and warrant that I have authority to do so.

DGB3hkdgJrxv9eDoWK1A2NGcaN5UGv8voF8U5MOgpYhVJgUlNnZvIQuqfUyKuba

### CODE REVIEW

**Comment by ttmc** [comment]
Hi @MisterDr 

Before we can merge this pull request, we need you or your organization to agree to one of our contributor agreements. One of the big concerns for people using and developing open source software is that someone who contributed to the code might claim the code infringes on their copyright or patent. To guard against this, we ask all our contributors to sign a Contributor License Agreement. This gives us the right to use the code contributed and any patents the contribution relies on. It also gives us and our users comfort that they won't be sued for using open source software. We know it's a hassle, but it makes the project more reliable in the long run. Thank you for your understanding and your contribution!

If you are contributing on behalf of yourself (and not on behalf of your employer or another organization you are part of) then you should:

1. Go to: https://www.bigchaindb.com/cla/
2. Read the Individual Contributor Agreement
3. Fill in the form "For Individuals"
4. Check the box to agree
5. Click the SEND button

If you're contributing as an employee, and/or you want all employees of your employing organization to be covered by our contributor agreement, then someone in your organization with the authority to enter agreements on behalf of all employees must do the following:

1. Go to: https://www.bigchaindb.com/cla/
2. Read the Entity Contributor Agreement
3. Fill in the form "For Organizations”
4. Check the box to agree
5. Click the SEND button

We will email you (or your employer) with further instructions.

**Comment by ttmc** [comment]
Sorry we didn't respond to this PR sooner. We've all been super-busy on the `tendermint` branch (i.e. Tendermint integration).

**Comment by kansi** [comment]
@MisterDr I think necessary test cases could be added [here](https://github.com/bigchaindb/bigchaindb/blob/master/tests/backend/mongodb/test_queries.py) and [here](https://github.com/bigchaindb/bigchaindb/blob/master/tests/web/test_assets.py)

**Comment by ttmc** [comment]
@MisterDr We got the email to notify us that you agreed to our CLA and now there's one last step: you have to copy a special block of text from that email to the comments in this pull request (as evidence that the controller of the @MisterDr GitHub account got that email).

**Comment by kansi** [comment]
We will be sharing a blog post regarding how to query data directly from MongoDB which in my opinion will implicitly address this scenario.

**Pull request closed without merging**
