### PR TITLE
Copy-edited the log rotation page (docs)

### PR DESCRIPTION
**Pull request by ttmc**
I did my best not to change the meaning of anything in the page. I just rearranged the three subsections (MongoDB, BigchainDB Server, Tendermint) to have parallel structure.

- Changed the titles to include both "Logging" and "Log Rotation"
- Added a hyperlink to MongoDB's docs about logging (and kept the existing link to the MongoDB docs about log rotation).
- Fixed the two hyperlinks to **How to Set Up a BigchainDB Network**.
- Added link to the BigchainDB Server configuration settings related to logging.
- In the **Troubleshooting** page, added a link to the page about **Logging and Log Rotation**.

### CODE REVIEW

**Comment by ttmc** [comment]
@muawiakh While setting up the new testnet, I noticed that `bigchaindb.log` and `bigchaindb-errors.log` were being written to `$HOME`, not `$HOME/.bigchaindb-monit/logs`.

@shahbazn said that's because those files get written to a locations configured in the BigchainDB config file, and the default location is `$HOME`.

The benchmark logs do get written to `$HOME/.bigchaindb-monit/logs`.

I will make a commit to update this PR.

**Comment by muawiakh** [comment]
This happened because when we run `bigchaindb configure` in the simple-network guide. It sets default to `$HOME`. Thats why they are not under `$HOME/.bigchaindb-monit/logs`

**Comment by ttmc** [comment]
Don't BigchainDB and Tendermint have to be configured (i.e. don't their config files have to be created and/or edited) before using Monit to run them?

I looked in `bigchaindb-monit-config` and it seems to only redirect the logs that were being sent to stdout, i.e. the benchmark logs.

**Comment by ttmc** [comment]
@muawiakh I made the commit mentioned above. I also removed the mention of `bigchaindb-benchmark.log` because it's going away anyhow: see issue #2560

**Comment by muawiakh** [comment]
I am thinking how we can make sure when we use Monit, the logs for BigchainDB and Tendermint are under `~/.bigchaindb-monit/logs/` OR we can specify the path to the log file. Because currently `bigchaindb configure` or `bigchaindb start` does not take the log file configuration and it is a bit inconsistent.

**Comment by ttmc** [comment]
@muawiakh  If we change the BigchainDB configuration settings `log.file` or `log.error_file` to something other than the default values (`~/bigchaindb.log` and `~/bigchaindb-errors.log`), will BigchainDB Server not care and continue writing the logs to those locations? If so, then that is a bug.

If those configuration settings do work, then I suppose the Monit script could just use them to change the log files to be under `~/.bigchaindb-monit/logs/`

**Comment by ttmc** [comment]
@muawiakh I just did a little test where I changed the values of `log.file` and `log.error_file` in my BigchainDB config file (in `~/.bigchaindb`) to something other than the default values. It worked: when I ran BigchainDB, those log files got written to locations that I specified.

**Comment by muawiakh** [comment]
Needs to be updated, `benchmark` logs were removed. Also can we make sure we only run `bigchaindb configure` when inside ~/.bigchaindb-monit/logs?

**Pull request merged**
