### PR TITLE
Update cc API usage

### PR DESCRIPTION
**Pull request by TimDaub**
This is the fix related to: https://github.com/bigchaindb/cryptoconditions/pull/15

We can merge as soon as cc was pushed to pipy.

### CODE REVIEW

**Comment by diminator** [comment]
I'm guessing the tests fail because of the cc version that's not created, hence not on pip

**Comment by diminator** [comment]
can you also have a look at `docs/servers/python-server-api-examples.md` ?

**Comment by TimDaub** [comment]
> I'm guessing the tests fail because of the cc version that's not created, hence not on pip

right, they'll pass once cc was updated on pip and this branch's cc version is bumped

> can you also have a look at docs/servers/python-server-api-examples.md ?

sure!

**Comment by diminator** [comment]
you may remove
https://github.com/bigchaindb/bigchaindb/pull/373/files#diff-aa177506e0b8b2feca9e5257590163e3R538

**Comment by diminator** [comment]
otherwise :+1:

**Comment by diminator** [comment]
if @r-marques approves, then you can merge

**Comment by r-marques** [comment]
:+1:

**Pull request merged**
