### PR TITLE
Docker image optimization.

### PR DESCRIPTION
**Pull request by anryko**
Optimized Dockerfile to create lightweight image.

Image size comparison:
```bash
bigchaindb/bigchaindb   latest              f7ac62515201        7 days ago          518 MB
local-bigchaindb-my2    latest              0d7b6ceae367        49 minutes ago      274 MB
```

### CODE REVIEW

**Comment by krish7919** [comment]
@anryko: Thanks for the PR. I am currently in the midst of something now. Will have a look later today or tomorrow.

**Comment by ttmc** [comment]
Hi @anryko 

Before we can merge this pull request, we need you or your organization to agree to one of our contributor agreements. One of the big concerns for people using and developing open source software is that someone who contributed to the code might claim the code infringes on their copyright or patent. To guard against this, we ask all our contributors to sign a Contributor License Agreement. This gives us the right to use the code contributed and any patents the contribution relies on. It also gives us and our users comfort that they won't be sued for using open source software. We know it's a hassle, but it makes the project more reliable in the long run. Thank you for your understanding and your contribution!

If you are contributing on behalf of yourself (and not on behalf of your employer or another organization you are part of) then you should:

1. Go to: https://www.bigchaindb.com/cla/
2. Read the Individual Contributor Agreement
3. Fill in the form "For Individuals"
4. Check the box to agree
5. Click the SEND button

If you're contributing as an employee, and/or you want all employees of your employing organization to be covered by our contributor agreement, then someone in your organization with the authority to enter agreements on behalf of all employees must do the following:

1. Go to: https://www.bigchaindb.com/cla/
2. Read the Entity Contributor Agreement
3. Fill in the form "For Organizations”
4. Check the box to agree
5. Click the SEND button

We will email you (or your employer) with further instructions.

**Comment by anryko** [comment]
@ttmc done

**Comment by anryko** [comment]
This is to confirm that I agreed to and accepted the BigchainDB Individual Contributor Agreement at https://www.bigchaindb.com/cla/ and to represent and warrant that I have authority to do so.

Z1aAcC6rfuxbqjBoyd6MTHiGTYkDlQPOU4gpROl4F3yOcTwGGDqJtFxjIuCBVNr

**Comment by ttmc** [comment]
Thanks @anryko!

@krish7919 The CLA step is cleared.

**Comment by krish7919** [comment]
LGTM. Thanks @anryko !

**Comment by anryko** [comment]
You are very welcome :). Thanks for the quick merge!

**Pull request merged**
